### ISSUE TITLE
Error msg for same fileName but different fileFormat.

### ISSUE THREAD

**Issue by LenChang** [monstahq/MONSTA-Box#21] opened 2015-05-27 07:01 UTC
Hi, i found a situation that if i upload a same filename but different fileFormat. It will make a mistake seem below. Is it a bug?
![error msg for ftp](https://cloud.githubusercontent.com/assets/9037287/7830563/25dcc620-0481-11e5-9dee-48480701fb3d.png)

**Comment by LenChang** [comment] 2015-05-27 07:01
Version:1.5.3. Thanks!

**Comment by greecemunky** [comment] 2015-06-03 11:47
In index.php - function getMaxStrLen, just before the **foreach** line, add a new line e.g.
**$maxLen = 0;**

**Comment by monstaftp** [comment] 2015-06-09 03:59
I'll check this out and fix in next release, thanks.

**Comment by greecemunky** [comment] 2015-07-03 04:57
This could be considered a dupe of #1, but I can introduce a fix for this one to close it off.

**Comment by greecemunky** [comment] 2015-07-27 06:40
@LenChang Try with the latest version, it should be resolved.

**Comment by LenChang** [comment] 2015-07-29 11:19
OK. I will try it. Thanks a lot!

**Comment by greecemunky** [comment] 2016-04-06 23:34
@monstahq I think this one can be closed.

**Closed** 2016-04-06 23:36 UTC
